cmake_minimum_required(VERSION 3.0.2)
project(robotic_fish_acoustic)
find_package(catkin REQUIRED COMPONENTS message_generation rospy std_msgs robotic_fish_io)
catkin_python_setup()
add_message_files(FILES QuadrantProbabilities.msg)
generate_messages(DEPENDENCIES std_msgs)
catkin_package(CATKIN_DEPENDS message_runtime rospy std_msgs robotic_fish_io)
catkin_install_python(PROGRAMS scripts/quadrant_node.py scripts/replay_quadrants.py DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
install(DIRECTORY launch DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
if(CATKIN_ENABLE_TESTING)
  catkin_add_nosetests(test/test_core.py)
endif()
